node {
    def app

    stage('Clone Repository') {
        // This checks out the source code from the GitHub repo configured in Jenkins
        checkout scm
    }

    stage('Build Image') {
        // Builds Docker image using Dockerfile in repo
        app = docker.build("jnaresh5021/custom_image2")
    }

    stage('Test Image') {
        // Runs a simple test inside a temporary container
        app.inside {
            sh 'echo "Test Passed"'
        }
    }

    stage('Push Image') {
        // Logs into Docker Hub and pushes image with two tags
        docker.withRegistry('https://index.docker.io/v1/', 'Docker_Hub_Credentials') {
            app.push("${env.BUILD_NUMBER}")  // unique tag per build
            app.push("latest")               // always points to newest build
        }
    }
}
